# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import resource_pool_pb2 as resource__pool__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in resource_pool_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ResourcePoolStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableResourceStatus = channel.unary_unary(
                '/keti.rpm.v1.ResourcePool/GetAvailableResourceStatus',
                request_serializer=resource__pool__pb2.GetAvailableResourceStatusRequest.SerializeToString,
                response_deserializer=resource__pool__pb2.AvailableResourceStatus.FromString,
                _registered_method=True)
        self.GetModelExecutionHistory = channel.unary_unary(
                '/keti.rpm.v1.ResourcePool/GetModelExecutionHistory',
                request_serializer=resource__pool__pb2.GetModelExecutionHistoryRequest.SerializeToString,
                response_deserializer=resource__pool__pb2.ModelExecutionHistory.FromString,
                _registered_method=True)
        self.UpdateAllocationDecision = channel.unary_unary(
                '/keti.rpm.v1.ResourcePool/UpdateAllocationDecision',
                request_serializer=resource__pool__pb2.UpdateAllocationDecisionRequest.SerializeToString,
                response_deserializer=resource__pool__pb2.UpdateAllocationDecisionResult.FromString,
                _registered_method=True)
        self.UpsertModelExecutionHistory = channel.unary_unary(
                '/keti.rpm.v1.ResourcePool/UpsertModelExecutionHistory',
                request_serializer=resource__pool__pb2.UpsertModelExecutionHistoryRequest.SerializeToString,
                response_deserializer=resource__pool__pb2.ModelExecutionHistory.FromString,
                _registered_method=True)


class ResourcePoolServicer:
    """Missing associated documentation comment in .proto file."""

    def GetAvailableResourceStatus(self, request, context):
        """C-RP-01 선택 파티션 가용 자원·점유 상태 조회
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelExecutionHistory(self, request, context):
        """C-RP-02 모델 실행 이력 조회
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAllocationDecision(self, request, context):
        """C-RP-03 스케줄링 결과 등록·갱신 (RESERVED / RELEASED)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertModelExecutionHistory(self, request, context):
        """실행 결과 저장 (모델 실행 이력 upsert — F-RP-06)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResourcePoolServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableResourceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableResourceStatus,
                    request_deserializer=resource__pool__pb2.GetAvailableResourceStatusRequest.FromString,
                    response_serializer=resource__pool__pb2.AvailableResourceStatus.SerializeToString,
            ),
            'GetModelExecutionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelExecutionHistory,
                    request_deserializer=resource__pool__pb2.GetModelExecutionHistoryRequest.FromString,
                    response_serializer=resource__pool__pb2.ModelExecutionHistory.SerializeToString,
            ),
            'UpdateAllocationDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAllocationDecision,
                    request_deserializer=resource__pool__pb2.UpdateAllocationDecisionRequest.FromString,
                    response_serializer=resource__pool__pb2.UpdateAllocationDecisionResult.SerializeToString,
            ),
            'UpsertModelExecutionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertModelExecutionHistory,
                    request_deserializer=resource__pool__pb2.UpsertModelExecutionHistoryRequest.FromString,
                    response_serializer=resource__pool__pb2.ModelExecutionHistory.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'keti.rpm.v1.ResourcePool', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('keti.rpm.v1.ResourcePool', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResourcePool:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAvailableResourceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keti.rpm.v1.ResourcePool/GetAvailableResourceStatus',
            resource__pool__pb2.GetAvailableResourceStatusRequest.SerializeToString,
            resource__pool__pb2.AvailableResourceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelExecutionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keti.rpm.v1.ResourcePool/GetModelExecutionHistory',
            resource__pool__pb2.GetModelExecutionHistoryRequest.SerializeToString,
            resource__pool__pb2.ModelExecutionHistory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAllocationDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keti.rpm.v1.ResourcePool/UpdateAllocationDecision',
            resource__pool__pb2.UpdateAllocationDecisionRequest.SerializeToString,
            resource__pool__pb2.UpdateAllocationDecisionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertModelExecutionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keti.rpm.v1.ResourcePool/UpsertModelExecutionHistory',
            resource__pool__pb2.UpsertModelExecutionHistoryRequest.SerializeToString,
            resource__pool__pb2.ModelExecutionHistory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
